# General Settings
title = "Awestomates - An awesome place for new ostomies."
baseURL = "https://awestomates.netlify.app/" 
canonifyURLs = false
disableAliases = false
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true
languageCode = "en-US"
footnoteReturnLinkContents = '↩'
paginate = 6
rssLimit = 12
theme = "awestomates"
resourceDir = "resources"
summaryLength = 20
DefaultContentLanguage = "en"

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS", "JSON"]
section = ["HTML", "RSS", "SITEMAP", "JSON"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediaType = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# Menu Settings
[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "getting-started"
  name = "Getting Started"
  url = "#getting-started"
  weight = 2
[[menu.main]]
  identifier = "guides"
  name = "Guides"
  url = "guides"
  weight = 3

# Main Settings
[params]
defaultSkin = "light"  # select default UI: "light" or "dark"
dateFormat = "September 20, 2023"
authorName = "Kaska Miskolczi"
disqusComments = "awestomates" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "" #YOUR FORMSPREE URL
googleAnalytics = "" #YOUR GOOGLE ANALYTICS CODE

# Guides Settings
[params.guides]
homeNumOfItems = 12
layout = "list" # select works layout options: "grid" or "list"
[[params.guides.filters]]
name = "Pre-Op"
slug = "pre-op"

# Preloader Settings
[params.preloader]
logo = "images/logo.svg"
alt = "Awestomates"

# Header Settings
[params.header]
logo = "images/logo.svg"
logo_alt =  "Awestomates"

# Footer Settings
[params.footer]
copyright = "© 2023 <strong>Awestomates</strong>. All rights reserved"
developer = "Developed with <i class='fa fa-heartbeat'></i> by <strong><a target='_blank' href='https://linkedin.com/in/rosenfaden'>Kaska</a></strong>"

# Social Settings
[[params.social]]
title = "Twitter"
icon = "fab fa-twitter"
url = "https://www.twitter.com/"
weight = 1
[[params.social]]
title = "Dribbble"
icon = "fab fa-dribbble"
url = "https://www.dribbble.com/"
weight = 2
[[params.social]]
title = "Behance"
icon = "fab fa-behance"
url = "https://www.behance.net/"
weight = 3

# Sidebar
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]

# Sitemap Settings
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

# Markup Settings
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = true
    latexDashes = true
    nofollowLinks = true
    noreferrerLinks = true
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "codepen"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2


# Minify Settings
[minify]
  disableCSS = true
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
      version = 2022
    [minify.tdewolff.json]
      keepNumbers = false
      precision = 0
    [minify.tdewolff.svg]
      keepComments = false
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false

# Build Settings
[build]
  writeStats = true

# Module Import Settings
# [module]
#   [[module.mounts]]
#     source = "assets"
#     target = "assets"
#   [[module.mounts]]
#     source = "static"
#     target = "static"

# Taxonomy Settings
[taxonomies]
  contributor = "contributors"
  tag = "tags"

# Relative Permalink Settings
[RelPermalinks]
  blog = "/blog/:title/"
  guides = "/guides/:title/"
